### ISSUE TITLE
RSpec tests: PhantomJS client died

### ISSUE THREAD

**Issue by 0is1** [Seravo/wordpress#25]
Any idea why PhantomJS keeps crashing during some rspec-tests?

For example wp-admin login test (after 9 successful tests with same kind of login tests):

```
describe "Login to wp-admin and test checkout-page link" do
      before do
        visit WP.siteurl('/wp-admin')
      end

      it "Log in to WordPress wp-admin" do
        within("#loginform") do
          fill_in 'log', :with => SOMELOGIN
          fill_in 'pwd', :with => SOMEPASS
        end
        click_button 'wp-submit'
        expect(page).to have_id "wp-admin-bar-pro-site"
      end
    end
```

And error:

```
Failure/Error: click_button 'wp-submit'
     
     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"796d6ac1-3767-482d-b797-ac959407cb0e","name":"click","args":[2,3]}
     # /var/lib/gems/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /var/lib/gems/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /var/lib/gems/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:180:in `click'
     # /var/lib/gems/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:17:in `command'
     # /var/lib/gems/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:131:in `click'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/node/element.rb:134:in `block in click'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/node/element.rb:134:in `click'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/node/actions.rb:39:in `click_button'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
     # /var/lib/gems/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./tests/rspec/merge-dev_site_onboarding_tests.rb:294:in `block (4 levels) in <top (required)>'
     # /var/lib/gems/2.2.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
     # /var/lib/gems/2.2.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
     # /var/lib/gems/2.2.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
     # /var/lib/gems/2.2.0/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /var/lib/gems/2.2.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'
```

I get same error also with tests like these:
```
describe 'Kaanon site tests' do

    before do
     visit WP.siteurl("/kaanon")
    end
 
    it "There's 'Kaanon | Pitkän tekstin ystävälle'-title" do
      expect(page.status_code).to be(200)
      expect(page).to have_title 'Kaanon | Pitkän tekstin ystävälle'
    end
 
 end
```

And error:
```
Failure/Error: visit WP.siteurl("/kaanon")
     
     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"9cd02d81-7812-4151-8108-f26e20ff9a16","name":"visit","args":["http://kehittamo.dev/kaanon",60]}
...
```

**Comment by ottok** [comment]
Thanks for reporting, we will look into this next week.

**Comment by anttiviljami** [comment]
This was a PhantomJS bug in a specific version. Fixed in newer vagrant images.
