### ISSUE TITLE
Pulling production database on first vagrant up fails

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#59]
I've the following `config.yml`: 
```
###
# Configuration for Vagrant
###
name: redacted
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: redacted.seravo.fi
  ssh_port: 10350
  url: https://redacted.seravo.fi
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - redacted.local
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
```

After cloning the project or destroying the Vagrant machine, trying to pull database from production results in failure, with this output: 
```
Bringing machine 'redacted-box' up with 'virtualbox' provider...
==> redacted-box: Importing base box 'seravo/wordpress'...
==> redacted-box: Matching MAC address for NAT networking...
==> redacted-box: Checking if box 'seravo/wordpress' is up to date...
==> redacted-box: Setting the name of the VM: redacted_redacted-box_1493710778163_61855
==> redacted-box: Fixed port collision for 22 => 2222. Now on port 2202.
==> redacted-box: Clearing any previously set network interfaces...
==> redacted-box: Preparing network interfaces based on configuration...
    redacted-box: Adapter 1: nat
    redacted-box: Adapter 2: hostonly
==> redacted-box: Forwarding ports...
    redacted-box: 22 (guest) => 2202 (host) (adapter 1)
==> redacted-box: Running 'pre-boot' VM customizations...
==> redacted-box: Booting VM...
==> redacted-box: Waiting for machine to boot. This may take a few minutes...
    redacted-box: SSH address: 127.0.0.1:2202
    redacted-box: SSH username: vagrant
    redacted-box: SSH auth method: private key
==> redacted-box: Machine booted and ready!
==> redacted-box: Checking for guest additions in VM...
    redacted-box: The guest additions on this VM do not match the installed version of
    redacted-box: VirtualBox! In most cases this is fine, but in rare cases it can
    redacted-box: prevent things such as shared folders from working properly. If you see
    redacted-box: shared folder errors, please make sure the guest additions within the
    redacted-box: virtual machine match the version of VirtualBox you have installed on
    redacted-box: your host and reload your VM.
    redacted-box:
    redacted-box: Guest Additions Version: 4.3.36
    redacted-box: VirtualBox Version: 5.1
==> redacted-box: [vagrant-hostsupdater] Checking for host entries
==> redacted-box: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  redacted  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  www.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  webgrind.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  adminer.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  mailcatcher.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  browsersync.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater]   192.168.53.210  info.redacted.local  # VAGRANT: dee86b3e07d41f5276d7b6dee0420ef8 (redacted-box) / 76259e76-17e9-4eef-863d-80a2ea3cbef2
==> redacted-box: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> redacted-box: Setting hostname...
==> redacted-box: Configuring and enabling network interfaces...
==> redacted-box: Mounting shared folders...
    redacted-box: /data/wordpress => /Users/k1sul1/Projects/wordpress-sites/redacted
==> redacted-box: Running provisioner: shell...
    redacted-box: Running: inline script
==> redacted-box: Running provisioner: shell...
    redacted-box: Running: inline script
==> redacted-box:  * Restarting nginx nginx
==> redacted-box:    ...done.
==> redacted-box: avahi-daemon stop/waiting
==> redacted-box: avahi-daemon start/running, process 2223
==> redacted-box: Setting custom domains in /etc/hosts/...
==> redacted-box: Generating ssh configs...
==> redacted-box: Running provisioner: shell...
    redacted-box: Running: /var/folders/k0/lsmj8qqj5hg81b8kzvm_stym0000gn/T/vagrant-shell20170502-5395-1hw792b.sh
==> redacted-box: no crontab for root
==> redacted-box: Running triggers after up...
checking for composer... yes
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> WordPress\Installer::symlinkWPContent
    redacted-box: Pull database from production? (no): y
==> redacted-box: Executing remote command "wp core install --url=https://redacted.local --title=Redacted         --admin_email=vagrant@redacted.local --admin_user=vagrant --admin_password=vagrant"...
==> redacted-box:
==> redacted-box:
==> redacted-box: Success: WordPress installed successfully.
==> redacted-box: Remote command execution finished.
==> redacted-box: Executing remote command "wp-pull-production-db"...
==> redacted-box:
==> redacted-box:
==> redacted-box: Saving backup of current development database in /data/db/pre-production-pull-backup.sql...
==> redacted-box: Success: Exported to 'pre-production-pull-backup-1493710805.sql'.
==> redacted-box: Define new and old siteurl for later search-replacing...
==> redacted-box: /usr/lib/ruby/vendor_ruby/highline.rb:862:in `get_line'
==> redacted-box: :
==> redacted-box: The input stream is exhausted.
==> redacted-box:  (
==> redacted-box: EOFError
==> redacted-box: )
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:885:in `get_response'
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:260:in `ask'
==> redacted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:223:in `agree'
==> redacted-box: 	from /usr/local/bin/wp-pull-production-db:48:in `<main>'
==> redacted-box: ==> Production site URL:
==> redacted-box: ==> Development site URL: https://redacted.local
==> redacted-box: ==> This is a normal WordPress single install.
==> redacted-box: Is the information above correct (yes/no)?
==> redacted-box: Please enter "yes" or "no".
==> redacted-box: Is the information above correct (yes/no)?
==> redacted-box: Remote command execution finished.
The remote command "wp-pull-production-db" returned a failed exit
code or an exception. The error output is shown below:

/usr/lib/ruby/vendor_ruby/highline.rb:862:in `get_line': The input stream is exhausted. (EOFError)
	from /usr/lib/ruby/vendor_ruby/highline.rb:885:in `get_response'
	from /usr/lib/ruby/vendor_ruby/highline.rb:260:in `ask'
	from /usr/lib/ruby/vendor_ruby/highline.rb:223:in `agree'
```

If I don't pull the database, I can just `vagrant ssh` into the machine, and run `wp-pull-production-db` without issues.

**Comment by ottok** [comment]
The `Pull database from production? (no)` during `vagrant up` fails quite often because wp-cli isn't corrently installed initially due to various reasons. In this paste you submitted we can see that ` ==> Production site URL:` is empty, so the `wp search-replace` cannot possible work. Why it is empty is the root cause, but that cannot be debugged from this output.

**Comment by spktklr** [comment]
You can succesfully pull production db with first `vagrant up` by creating a custom script via hooking up the Vagrantfile's vagrant-up-customizer.sh. Although you first have to alter the Vagrantfile to run it.

Set up your custom script to run https://github.com/Seravo/wp-palvelu-vagrant/blob/master/roles/scripts/files/wp-pull-production-db inside the machine.

However, you have to add `-o StrictHostKeyChecking=no` to the ssh command for it not to fail, as it wants to confirm the fingerprint on the first connect. I'd make a PR but this part makes it a bit dubious.

**Comment by ottok** [comment]
OK, now I was finally able to reproduce this. It happens only on the first 'vagrant up' and if you reply *yes* to the question *Pull database from production? (no)*

The output here is printed automatically, without any interactivity on the yes/no questions:
```
==> reducted-box: Define new and old siteurl for later search-replacing...
==> reducted-box: /usr/lib/ruby/vendor_ruby/highline.rb:862:in `get_line': The input stream is exhausted. (EOFError)
==> reducted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:885:in `get_response'
==> reducted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:260:in `ask'
==> reducted-box: 	from /usr/lib/ruby/vendor_ruby/highline.rb:223:in `agree'
==> reducted-box: 	from /usr/local/bin/wp-pull-production-db:48:in `<main>'
==> reducted-box: ==> Production site URL: 
==> reducted-box: ==> Development site URL: https://reducted.local
==> reducted-box: ==> This is a normal WordPress single install.
==> reducted-box: Is the information above correct (yes/no)?
==> reducted-box: Please enter "yes" or "no".
==> reducted-box: Is the information above correct (yes/no)?
==> reducted-box: Remote command execution finished.
The remote command "wp-pull-production-db" returned a failed exit
code or an exception. The error output is shown below:
```

The root cause is how the interactive yes/no questions fail to interact with the Vagrantfile running them in this situation.

**Comment by ottok** [comment]
The problem is in the wp-pull-production-db that did not support interactive mode: https://github.com/Seravo/wp-palvelu-vagrant/issues/41
